image: jonoh/docker-buildx-qemu@sha256:4fc5868d90c146563dace436cb1b850c2bd8055ff2e7d9d53fb4a83a7dc2969e

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  INDEV_IMAGE_NAME: $CI_REGISTRY_IMAGE:trunk-indev_CI-${CI_COMMIT_REF_NAME}
  BUILD_ARCHS: "linux/amd64,linux/arm64,linux/arm/v7"

# Prepare
.install_buildx_template: &install_buildx
  before_script:
    - update-binfmts --enable
    - docker buildx create --use
    - docker buildx inspect --bootstrap


# Build
build-ivp:
  stage: build
  <<: *install_buildx
  script:
    # Some of this can be simplified when moving MOOS-IvP to git and when the Dockerfile is embeded in the main moos-ivp
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker buildx build --push --platform "${BUILD_ARCHS}" -t $INDEV_IMAGE_NAME ./docker/moos-ivp
    - SVN_REV="r$(docker run --rm $INDEV_IMAGE_NAME svn info --show-item revision moos-ivp)" && export SVN_REV && echo "$SVN_REV"
    - docker tag $INDEV_IMAGE_NAME $CI_REGISTRY_IMAGE:${SVN_REV}-indev
    - docker push $CI_REGISTRY_IMAGE:${SVN_REV}-indev

# Test
test-build-check:
  image: "$INDEV_IMAGE_NAME"
  stage: test
  allow_failure: true
  script:
    - cd moos-ivp/
    - build-check.sh

test-unit-tests:
  image: "$INDEV_IMAGE_NAME"
  stage: test
  allow_failure: true
  script:
    - cd moos-ivp/ 
    - ./build-utests.sh
    - cd ivp/src_unit_tests 
    - ./alltest.sh

# Deploy
.before_script_template: &deploy_generic
  except:
    - merge_requests
    - external_pull_requests
  script:
    - docker pull $INDEV_IMAGE_NAME
    - SVN_REV="r$(docker run --rm $INDEV_IMAGE_NAME svn info --show-item revision moos-ivp)" && export SVN_REV
    - echo "$REGISTRY_PASSWD" | docker login --username $REGISTRY_USER --password-stdin $REGISTRY_URL
    - docker tag $INDEV_IMAGE_NAME ${REPO_PATH}:${SVN_REV}
    - docker tag $INDEV_IMAGE_NAME ${REPO_PATH}:trunk
    - docker push ${REPO_PATH}:${SVN_REV}
    - docker push ${REPO_PATH}:trunk

deploy-gitlab-registry:
  stage: deploy
  variables:
    REGISTRY_URL: "$CI_REGISTRY"
    REGISTRY_USER: "$CI_REGISTRY_USER"
    REGISTRY_PASSWD: "$CI_REGISTRY_PASSWORD"
    REPO_PATH: "$CI_REGISTRY_IMAGE"
  <<: *deploy_generic

deploy-docker-hub-registry:
  only:
    refs:
      - master
      - schedules
  stage: deploy
  variables:
    REGISTRY_URL: "docker.io"
    REGISTRY_USER: "$DOCKER_HUB_USERNAME"
    REGISTRY_PASSWD: "$DOCKER_HUB_PUSH_KEY"
    REPO_PATH: "${REGISTRY_URL}/moosivp/moos-ivp"
  <<: *deploy_generic
