image: docker:stable

services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-ivp:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:testing ./docker/moos-ivp
    - docker push $CI_REGISTRY_IMAGE:testing

