image: docker:19

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DEPLOY_ARCHS: "amd64 arm64 armv7"
  INDEV_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/indev:trunk_CI-${CI_PIPELINE_ID}"

# Build
.install_buildx_template: &build_generic
  stage: build
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - export NEW_IMAGE_NAME="${INDEV_IMAGE_NAME}-${BUILD_ARCH_NICE}" && echo $NEW_IMAGE_NAME
    - docker buildx build --push --platform "${BUILD_ARCH}" -t "$NEW_IMAGE_NAME" ./docker/moos-ivp
    - echo "Checking for existance of image ${INDEV_IMAGE_NAME}"
    - docker buildx imagetools inspect "${INDEV_IMAGE_NAME}" || export IMAGE_EXISTS="false"
    - if [[ "$IMAGE_EXISTS" == "false" ]]; then echo "Creating image..."; docker buildx imagetools create -t "${INDEV_IMAGE_NAME}" "$NEW_IMAGE_NAME"; fi
    - if [[ "$IMAGE_EXISTS" != "false" ]]; then echo "Appending to image..."; docker buildx imagetools create --append -t "${INDEV_IMAGE_NAME}" "$NEW_IMAGE_NAME"; fi


build-ivp:amd64:
  timeout: 1h
  variables:
    BUILD_ARCH: linux/amd64
    BUILD_ARCH_NICE: "amd64"
  <<: *build_generic

build-ivp:arm64:
  timeout: 3h
  variables:
    BUILD_ARCH: linux/arm64
    BUILD_ARCH_NICE: "arm64"
  <<: *build_generic

build-ivp:armv7:
  timeout: 3h
  variables:
    BUILD_ARCH: linux/arm/v7
    BUILD_ARCH_NICE: "armv7"
  <<: *build_generic
    
# Test
.test_common: &test_common
  stage: test
  image: "${INDEV_IMAGE_NAME}"
  allow_failure: true
  variables:
    GIT_STRATEGY: none
  before_script:
    - cd $HOME
    - ls
    - cd moos-ivp/

test-build-check:
  <<: *test_common
  script:
    - ./build-check.sh

test-unit-tests:
  <<: *test_common
  script:
    - ./build-utests.sh
    - cd ivp/src_unit_tests/
    - ./alltest.sh

# Deploy
.deploy_generic_imagetools: &deploy_generic_imagetools
  stage: deploy
  except:
   - merge_requests
   - external_pull_requests
  before_script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - export SVN_REV="r$(docker run --rm ${INDEV_IMAGE_NAME} svn info --show-item revision moos-ivp)" && echo $SVN_REV
    - echo "$REGISTRY_PASSWD" | docker login --username $REGISTRY_USER --password-stdin $REGISTRY_URL
  script:
    - docker buildx imagetools create --tag ${REPO_PATH}:${SVN_REV} $INDEV_IMAGE_NAME
    - docker buildx imagetools create --tag ${REPO_PATH}:trunk $INDEV_IMAGE_NAME

.deploy_generic_manifest: &deploy_generic_manifest
  stage: deploy
  except:
   - merge_requests
   - external_pull_requests
  before_script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - export SVN_REV="r$(docker run --rm ${INDEV_IMAGE_NAME} svn info --show-item revision moos-ivp)" && echo $SVN_REV
    - echo "$REGISTRY_PASSWD" | docker login --username $REGISTRY_USER --password-stdin $REGISTRY_URL
  script:
    # TODO dynamically get matching tags via registry API
    - for arch in $DEPLOY_ARCHS; do IMAGES="$IMAGES ${INDEV_IMAGE_NAME}-${arch}"; done
    - docker manifest create ${REPO_PATH}:${SVN_REV} ${IMAGES}
    - docker manifest create ${REPO_PATH}:trunk ${IMAGES}
    - docker manifest push --purge ${REPO_PATH}:${SVN_REV}
    - docker manifest push --purge ${REPO_PATH}:trunk

deploy-gitlab-registry:
  variables:
    REGISTRY_URL: "$CI_REGISTRY"
    REGISTRY_USER: "$CI_REGISTRY_USER"
    REGISTRY_PASSWD: "$CI_REGISTRY_PASSWORD"
    REPO_PATH: "$CI_REGISTRY_IMAGE"
  <<: *deploy_generic_manifest

deploy-docker-hub-registry:
  only:
    refs:
      - master
      - schedules
  variables:
    REGISTRY_URL: "docker.io"
    REGISTRY_USER: "$DOCKER_HUB_USERNAME"
    REGISTRY_PASSWD: "$DOCKER_HUB_PUSH_KEY"
    REPO_PATH: "${REGISTRY_URL}/moosivp/moos-ivp"
  <<: *deploy_generic_manifest
