image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  INDEV_IMAGE_NAME: $CI_REGISTRY_IMAGE:trunk-indev
  BUILD_ARCHS: "linux/amd64,linux/arm64,linux/arm/v7"

# Prepare
.install_buildx_template: &install_buildx
  before_script:
    # Thanks https://gitlab.com/com.hillnz.docker/docker-buildx-qemu/blob/master/Dockerfile
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - mkdir -p ~/.docker/cli-plugins
    - |
      wget -O - https://api.github.com/repos/docker/buildx/releases/latest | \
      grep "browser_download_url.*linux-amd64" | cut -d : -f 2,3 | tr -d \" | \
      xargs wget -O ~/.docker/cli-plugins/docker-buildx && \
      chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap


# Build
build-ivp:
  stage: build
  <<: *install_buildx
  script:
    # Some of this can be simplified when moving MOOS-IvP to git and when the Dockerfile is embeded in the main moos-ivp
    - docker buildx build --load --platform "${BUILD_ARCHS}" -t $INDEV_IMAGE_NAME ./docker/moos-ivp
    - SVN_REV="r$(docker run --rm $INDEV_IMAGE_NAME svn info --show-item revision moos-ivp)" && export SVN_REV && echo "$SVN_REV"
    - docker tag $INDEV_IMAGE_NAME $CI_REGISTRY_IMAGE:${SVN_REV}-indev
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $INDEV_IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE:${SVN_REV}-indev

# Test
test-build-check:
  stage: test
  script:
    - docker pull $INDEV_IMAGE_NAME
    - docker run $INDEV_IMAGE_NAME moos-ivp/build-check.sh || true

test-unit-tests:
  stage: test
  script:
    - docker pull $INDEV_IMAGE_NAME
    - docker run $INDEV_IMAGE_NAME /bin/bash -c 'moos-ivp/build-utests.sh && cd moos-ivp/ivp/src_unit_tests && ./alltest.sh || true'

# Deploy
.before_script_template: &deploy_generic
  except:
    - merge_requests
    - external_pull_requests
  script:
    - docker pull $INDEV_IMAGE_NAME
    - SVN_REV="r$(docker run --rm $INDEV_IMAGE_NAME svn info --show-item revision moos-ivp)" && export SVN_REV
    - echo "$REGISTRY_PASSWD" | docker login --username $REGISTRY_USER --password-stdin $REGISTRY_URL
    - docker tag $INDEV_IMAGE_NAME ${REPO_PATH}:${SVN_REV}
    - docker tag $INDEV_IMAGE_NAME ${REPO_PATH}:trunk
    - docker push ${REPO_PATH}:${SVN_REV}
    - docker push ${REPO_PATH}:trunk

deploy-gitlab-registry:
  stage: deploy
  variables:
    REGISTRY_URL: "$CI_REGISTRY"
    REGISTRY_USER: "$CI_REGISTRY_USER"
    REGISTRY_PASSWD: "$CI_REGISTRY_PASSWORD"
    REPO_PATH: "$CI_REGISTRY_IMAGE"
  <<: *deploy_generic

deploy-docker-hub-registry:
  only:
    refs:
      - master
      - schedules
  stage: deploy
  variables:
    REGISTRY_URL: "docker.io"
    REGISTRY_USER: "$DOCKER_HUB_USERNAME"
    REGISTRY_PASSWD: "$DOCKER_HUB_PUSH_KEY"
    REPO_PATH: "${REGISTRY_URL}/moosivp/moos-ivp"
  <<: *deploy_generic
