image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  INDEV_IMAGE_NAME: $CI_REGISTRY_IMAGE:trunk-indev

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.before_script_template: &deploy_generic
  except:
    - merge_requests
    - external_pull_requests
  script:
    - docker pull $INDEV_IMAGE_NAME
    - SVN_REV="r$(docker run $INDEV_IMAGE_NAME svn info --show-item revision moos-ivp)" && export SVN_REV
    - docker login --username $REGISTRY_USER --password $REGISTRY_PASSWD $REGISTRY_URL
    - docker tag $INDEV_IMAGE_NAME ${REPO_PATH}:${SVN_REV}
    - docker tag $INDEV_IMAGE_NAME ${REPO_PATH}:trunk
    - docker push ${REPO_PATH}:${SVN_REV}
    - docker push ${REPO_PATH}:trunk

build-ivp:
  stage: build
  script:
    # Some of this can be simplified when moving MOOS-IvP to git and when the Dockerfile is embeded in the main moos-ivp
    - docker build -t $INDEV_IMAGE_NAME ./docker/moos-ivp
    - SVN_REV="r$(docker run $INDEV_IMAGE_NAME svn info --show-item revision moos-ivp)" && export SVN_REV && echo "$SVN_REV"
    - docker tag $INDEV_IMAGE_NAME $CI_REGISTRY_IMAGE:${SVN_REV}-indev
    - docker push $INDEV_IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE:${SVN_REV}-indev

test-build-check:
  stage: test
  script:
    - docker pull $INDEV_IMAGE_NAME
    - docker run $INDEV_IMAGE_NAME moos-ivp/build-check.sh || true

test-unit-tests:
  stage: test
  script:
    - docker pull $INDEV_IMAGE_NAME
    - docker run $INDEV_IMAGE_NAME /bin/bash -c 'moos-ivp/build-utests.sh && cd moos-ivp/ivp/src_unit_tests && ./alltest.sh || true'


deploy-gitlab-registry:
  stage: deploy
  variables:
    REGISTRY_URL: "$CI_REGISTRY"
    REGISTRY_USER: "$CI_REGISTRY_USER"
    REGISTRY_PASSWD: "$CI_REGISTRY_PASSWORD"
    REPO_PATH: "$CI_REGISTRY_IMAGE"
  <<: *deploy_generic

deploy-docker-hub-registry:
  stage: deploy
  variables:
    REGISTRY_URL: "docker.io"
    REGISTRY_USER: "$DOCKER_HUB_USERNAME"
    REGISTRY_PASSWD: "$DOCKER_HUB_PUSH_KEY"
    REPO_PATH: "${REGISTRY_URL}/moosivp/moos-ivp"
  <<: *deploy_generic
